const getCategoryIcon = (categoryName) => {
    const iconMap = {
      // Gradnja i renoviranje
      'Gradnja': '🏗️',
      'Renoviranje': '🔨',
      'Keramika': '🧱',
      'Parket': '🪵',
      'Krov': '🏠',
      'Fasada': '🎨',
      'Vodovod': '🚰',
      'Elektrika': '⚡',
      'Grijanje': '🔥',
      'Klima': '❄️',
      'Izolacija': '🧊',
      'Stolarija': '🪟',
      'Vrata': '🚪',
      'Prozori': '🪟',
      'Balkon': '🏡',
      'Terasa': '🌿',
      'Bazen': '🏊',
      'Vrt': '🌱',
      'Ogradni zid': '🧱',
      'Asfalt': '🛣️',
      
      // IT i tehnologija
      'IT usluge': '💻',
      'Web dizajn': '🌐',
      'Programiranje': '👨‍💻',
      'Mreže': '🌐',
      'Sigurnost': '🔒',
      'Cloud': '☁️',
      'Mobilne aplikacije': '📱',
      'E-commerce': '🛒',
      'SEO': '🔍',
      'Digitalni marketing': '📈',
      
      // Obrazovanje
      'Obrazovanje': '📚',
      'Jezici': '🗣️',
      'Muzika': '🎵',
      'Sport': '⚽',
      'Ples': '💃',
      'Slikanje': '🎨',
      'Fotografija': '📸',
      'Kuhanje': '👨‍🍳',
      
      // Zdravlje i ljepota
      'Zdravlje': '🏥',
      'Fizioterapija': '💪',
      'Masage': '💆',
      'Kozmetika': '💄',
      'Nokti': '💅',
      'Kosa': '💇',
      'Tatuaže': '🎨',
      'Fitness': '💪',
      'Joga': '🧘',
      
      // Usluge
      'Čišćenje': '🧽',
      'Pranje': '👕',
      'Dostava': '🚚',
      'Prevoz': '🚗',
      'Taxi': '🚕',
      'Dostava hrane': '🍕',
      'Dostava paketa': '📦',
      'Selidba': '📦',
      'Skladištenje': '🏪',
      
      // Automobili
      'Automobili': '🚗',
      'Servis': '🔧',
      'Dijagnostika': '🔍',
      'Gume': '🛞',
      'Akumulator': '🔋',
      'Auto perionica': '🚿',
      'Auto škola': '🚗',
      
      // Ostalo
      'Pravne usluge': '⚖️',
      'Računovodstvo': '📊',
      'Marketing': '📢',
      'Dizajn': '🎨',
      'Video': '🎬',
      'Organizacija događaja': '🎉',
      'Konzultacije': '💼',
      'Prijenos': '📡',
      
      // Dodatne specifične kategorije
      'Instalacije': '🔧',
      'Popravci': '🔨',
      'Montaža': '⚙️',
      
      // Dodatne kategorije koje se često koriste
      
      // Još dodatnih kategorija
      'Financije': '💰',
      'Osiguranje': '🛡️',
      'Nekretnine': '🏠',
      'Prodaja': '🛒',
      'Kupnja': '🛍️',
      'Najam': '🏠',
      'Turizam': '✈️',
      'Putovanja': '🧳',
      'Hoteli': '🏨',
      'Restorani': '🍽️',
      'Kafići': '☕',
      'Bars': '🍻',
      'Zabava': '🎭',
      'Kazalište': '🎭',
      'Kino': '🎬',
      'Koncerti': '🎵',
      'Festivali': '🎪',
      'Teretana': '🏋️',
      'Tenis': '🎾',
      'Fudbal': '⚽',
      'Košarka': '🏀',
      'Rukomet': '🤾',
      'Vaterpolo': '🤽',
      'Plivanje': '🏊',
      'Trčanje': '🏃',
      'Biciklizam': '🚴',
      'Planinarenje': '🥾',
      'Skijanje': '🎿',
      'Surfing': '🏄',
      'Ribolov': '🎣',
      'Lov': '🏹',
      'Kampiranje': '⛺',
      'Alpinizam': '🧗',
      'Paragliding': '🪂',
      'Padobranstvo': '🪂',
      'Avijacija': '✈️',
      'Helikopter': '🚁',
      'Brod': '⛵',
      'Jahta': '⛵',
      'Motocikl': '🏍️',
      'Skuter': '🛵',
      'Bicikl': '🚲',
      'Električni bicikl': '🚲',
      'Skateboard': '🛹',
      'Rolice': '🛼',
      'Sanke': '🛷',
      'Ski': '🎿',
      'Snowboard': '🏂',
      'Kajak': '🛶',
      'Kanua': '🛶',
      'Rafting': '🛶',
      'Diving': '🤿',
      'Snorkeling': '🤿',
      'Speleologija': '🕳️',
      'Geocaching': '🗺️',
      'Astronomija': '🔭',
      'Dron': '🚁',
      '3D print': '🖨️',
      'Laserski graviranje': '⚡',
      'CNC obrada': '⚙️',
      'Struganje': '🔧',
      'Brušenje': '🔧',
      'Varjenje': '🔥',
      'Limanje': '🔧',
      'Bojanje': '🎨',
      'Tapetiranje': '🎨',
      'Staklo': '🪟',
      'Metal': '⚙️',
      'Drvo': '🪵',
      'Plastika': '🧱',
      'Tekstil': '🧵',
      'Koža': '👜',
      'Papir': '📄',
      'Karton': '📦',
      'Guma': '🛞',
      'Silikon': '🧱',
      'Epoksid': '🧱',
      'Akril': '🎨',
      'Ulje': '🖼️',
      'Tempera': '🎨',
      'Akvarel': '🎨',
      'Pastel': '🎨',
      'Ugljen': '🖤',
      'Kreda': '🖍️',
      'Marker': '🖊️',
      'Olovka': '✏️',
      'Kemijska olovka': '✏️',
      'Kist': '🖌️',
      'Špachtla': '🔧',
      'Valjak': '🔧',
      'Šmirgl': '🔧',
      'Brusilica': '🔧',
      'Bušilica': '🔧',
      'Odvijač': '🔧',
      'Ključ': '🔧',
      'Čekić': '🔨',
      'Kliješta': '🔧',
      'Pila': '🔧',
      'Motorna pila': '🔧',
      'Kompresor': '🔧',
      'Generator': '⚡',
      'Inverter': '⚡',
      'UPS': '⚡',
      'Baterija': '🔋',
      'Solarni panel': '☀️',
      'Vjetroelektrana': '💨',
      'Geotermalna': '🌋',
      'Hidroelektrana': '💧',
      'Nuklearna': '☢️',
      'Nafta': '🛢️',
      'Plin': '🔥',
      'Biomasa': '🌱',
      'Biogas': '💨',
      'Vodik': '💨',
      'Etanol': '🍷',
      'Biodizel': '🛢️',
      'Električna energija': '⚡',
      'Toplinska energija': '🔥',
      'Mehanička energija': '⚙️',
      'Kemijska energija': '🧪',
      'Nuklearna energija': '☢️',
      'Gravitacijska energija': '🌍',
      'Elastična energija': '🔗',
      'Magnetna energija': '🧲',
      'Elektromagnetna energija': '📡',
      'Svjetlosna energija': '💡',
      'Zvučna energija': '🔊',
      'Tlačna energija': '💨',
      'Kinetička energija': '🏃',
      'Potencijalna energija': '⛰️',
      'Termalna energija': '🌡️',
      'Radiantna energija': '☀️',
      
      // Kategorije iz baze podataka
      'Autoelektričar': '🔧',
      'Autolimarija i farbanje': '🎨',
      'Automehaničar': '🔧',
      'Bazenski radovi': '🏊',
      'Bravarski radovi': '🔨',
      'Čišćenje fasada': '🧽',
      'Dezinsekcija i deratizacija': '🐛',
      'Dimnjačar': '🏠',
      'Dizalice i platforme': '🏗️',
      'Električar': '⚡',
      'Električne instalacije': '🔌',
      'Električni paneli': '⚡',
      'LED rasvjeta': '💡',
      'Event usluge': '🎉',
      'Fasader': '🎨',
      'Fotografski servisi': '📸',
      'Frizerske usluge': '💇',
      'Gips-karton': '🧱',
      'Kamenarske usluge': '🗿',
      'Keramičar': '🧱',
      'Fugiranje': '🔧',
      'Kamene ploče': '🗿',
      'Mosaik i dekorativne pločice': '🎨',
      'Klima uređaji': '❄️',
      'Centralna klima': '❄️',
      'Mobilni klima uređaji': '❄️',
      'Servis klima uređaja': '🔧',
      'Kozmetičke usluge': '💄',
      'Krovopokrivač': '🏠',
      'Limarski radovi': '🔧',
      'Masažne usluge': '💆',
      'Moler-Slikar': '🎨',
      'Bojanje zidova': '🎨',
      'Dekorativne tehnike': '🎨',
      'Gletovanje': '🔧',
      'Ograđivanje': '🧱',
      'Parketar': '🔨',
      'Plinoinstalatér': '🔥',
      'Podne obloge': '🔨',
      'Popravak kućanskih aparata': '🔧',
      'Prevodilački servisi': '🗣️',
      'Računalni servisi': '💻',
      'Računovodstvene usluge': '📊',
      'Selidbe': '📦',
      'Šetanje pasa': '🐕',
      'Sigurnosni sustavi': '🔒',
      'Soboslikarski radovi': '🎨',
      'Staklarski radovi': '🪟',
      'Stolar': '🪚',
      'Izrada namještaja': '🪑',
      'Parket i laminat': '🪵',
      'Ugradnja kuhinja': '🍳',
      'Terase i pergole': '🌿',
      'Transport robe': '🚚',
      'Tutorstvo': '📚',
      'Ugradnja rolled': '🪟',
      'Ventilacija': '💨',
      'Veterinarske usluge': '🐕',
      'Video produkcija': '🎬',
      'Vodoinstalater': '🚰',
      'Grijanje vode': '🔥',
      'Kanalizacija': '🚽',
      'Popravak sanitarija': '🚽',
      'Vrtlar': '🌱',
      'Vulkanizer': '🚗',
      'Zidar': '🧱'
    };
    
    
    return iconMap[categoryName] || '🛠️';
  };