FROM node:20-bookworm-slim AS prisma-tasks
WORKDIR /app

# System deps za Prisma CLI
RUN apt-get update -y && apt-get install -y --no-install-recommends     openssl ca-certificates && rm -rf /var/lib/apt/lists/*

# Trebaju nam devDependencies jer Prisma CLI obično stoji u devDeps
COPY package*.json ./
# Ako postoji lock -> ci; inače -> install (trebaju devDeps za Prisma CLI)
RUN if [ -f package-lock.json ]; then \
	RUN ls -la
      npm ci --ignore-scripts; \
    else \
	RUN ls -la
      npm install --ignore-scripts; \
    fi

# Multi-file schema layout
COPY prisma ./prisma

ENV PRISMA_GENERATE_SKIP_AUTOINSTALL=1
ENV PRISMA_OPENSSL_VERSION=3.0.x

# Generiraj Prisma Client
RUN npx prisma generate --schema=./prisma

# Default: pomoć; u CI/one-off zadatku override-at će se "command"
CMD ["sh","-lc","npx prisma --help"]
