name: Build uslugar

on:
  push:
    branches: [ main, staging ]
    paths:
      - 'uslugar/**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION || secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID || secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN || secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ (vars.AWS_ACCOUNT_ID || secrets.AWS_ACCOUNT_ID) }}.dkr.ecr.${{ (vars.AWS_REGION || secrets.AWS_REGION) }}.amazonaws.com
  ECR_REPO: uslugar
  CONTEXT: uslugar

concurrency:
  group: uslugar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ github.ref_name }}-${{ github.sha }}
